name: CI

on:
  push:
    branches:
      - main # Adjust if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mysql image
        working-directory: ./mysql
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/rpa-mysql:latest .
          docker push ghcr.io/${{ github.repository_owner }}/rpa-mysql:latest
            
      - name: Build and push backend image
        working-directory: ./backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/rpa-backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/rpa-backend:latest

      - name: Build and push frontend image
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/rpa-frontend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/rpa-frontend:latest
